### ISSUE TITLE
No such file or directory, /Users/username/snippets

### ISSUE THREAD

**Issue by hiaw** [abingham/elm-yasnippets#2]
Hi,

I found that installing your snippets cause yasnippets to create error where it can't find the snippets directory in what every directory I happened to be working in. e.g. `/Users/username/snippets`

I found [Another similar issue](https://github.com/capitaomorte/yasnippet/issues/529) with another yasnippets. Perhaps you can have a look to see if you can solve it?

Thanks.

**Comment by abingham** [comment]
Hmm, sorry about that! If you could, try out the [fix-snippets-dir](https://github.com/abingham/elm-yasnippets/tree/fix-snippets-dir) branch and let me know if that fixes things for you.

**Comment by hiaw** [comment]
Yeap. That works for me~ Thanks a lot

**Comment by abingham** [comment]
OK, I've merged that into master. Thanks for reporting it.
